BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS Aluno (
	cpf	INTEGER(11),
	matricula	VARCHAR(13) NOT NULL,
	nome	VARCHAR(40) NOT NULL,
	data_nascimento	VARCHAR(10) NOT NULL,
	telefone	VARCHAR(11) NOT NULL,
	email	VARCHAR(35) NOT NULL,
	status	INTEGER(1) NOT NULL DEFAULT (1),
	PRIMARY KEY(cpf)
);
CREATE TABLE IF NOT EXISTS Curso (
	id	INTEGER,
	nome	VARCHAR(30) NOT NULL,
	turno	VARCHAR(10) NOT NULL,
	carga_horaria	INTEGER(4) NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS AlunoCurso (
	id		INTEGER,
	aluno_cpf	INTEGER(11) NOT NULL,
	curso_id	INTEGER NOT NULL,
	PRIMARY KEY(id AUTOINCREMENT),
	FOREIGN KEY(aluno_cpf) REFERENCES Aluno(cpf),
	FOREIGN KEY(curso_id) REFERENCES Curso(id)
);
COMMIT;
